version: "3.8"
services:
  anqicms:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: anqicms
    restart: unless-stopped
    ports:
      - "8001:8001"
    volumes:
      - ./config.json:/app/config.json
      - ./data:/app/data
      - ./cache:/app/cache
      - ./template:/app/template
      - ./public/uploads:/app/public/uploads
    networks:
      - wk_crm_kaka
    environment:
      - TZ=Asia/Shanghai

networks:
  wk_crm_kaka:
    external: true
